name: GitHub Pages Docs Generation

on:
  push:
    branches:
      - main
    paths:
      - "flake.nix"
      - "flake.lock"
      - "modules/**"
      - "docs/**"
  workflow_dispatch:

jobs:
  publish:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 1

      - uses: DeterminateSystems/nix-installer-action@v17

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Build documentation
        run: |
          nix build .#docs-html
          cp -r result/share/doc/equinix public
          unlink result

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
